Make pre-commit hook quieter

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -41,21 +41,36 @@ EOF
 fi
 
 set -e
+
 cd "$(git rev-parse --show-toplevel)"
+LOGS_DIR="$(pwd)/githooks/logs"
+mkdir -p "$LOGS_DIR"
+
+##### Scala-related tests ######################################################
+
+if [ -n "${SKIP_SCALA:-}" ]; then
+    SKIP_SCALAFMT='1'
+    SKIP_SBT_TESTS='1'
+    SKIP_E2E_TESTS='1'
+fi
 
 if [ -z "${SKIP_SCALAFMT:-}" ]; then
-    echo "Running scalafmt (skip by defining SKIP_SCALAFMT)..."
-    scalafmt --check --quiet --exclude ./lib,./src/test/aetherling,./src/test/shir || {
+    echo "Running scalafmt (skip by defining SKIP_SCALA or SKIP_SCALAFMT)..."
+    logs="$LOGS_DIR/scalafmt.log"
+    scalafmt --check --exclude ./lib,./src/test/aetherling,./src/test/shir >"$logs" 2>&1 || {
         echo "Some files are mis-formatted. Please format them using scalafmt."
+        echo "See $logs for details."
         exit 1
     }
     echo ""
 fi
 
 if [ -z "${SKIP_SBT_TESTS:-}" ]; then
-    echo "Running unit tests with sbt (skip by defining SKIP_SBT_TESTS)..."
-    sbt 'testQuick * -- -l mhir.testing.HardwareTest -l org.scalatest.tags.Slow' || {
+    echo "Running unit tests with sbt (skip by defining SKIP_SCALA or SKIP_SBT_TESTS)..."
+    logs="$LOGS_DIR/sbt_tests.log"
+    sbt 'testQuick * -- -l mhir.testing.HardwareTest -l org.scalatest.tags.Slow' >"$logs" 2>&1 || {
         echo "Unit tests failed."
+        echo "See $logs for details."
         exit 1
     }
     echo ""
@@ -66,58 +81,101 @@ if [ -e .venv/bin/activate ]; then
 fi
 
 if [ -z "${SKIP_E2E_TESTS:-}" ]; then
-    echo "Running end-to-end tests (skip by defining SKIP_E2E_TESTS)..."
+    echo "Running end-to-end tests (skip by defining SKIP_SCALA or SKIP_E2E_TESTS)..."
+    logs="$LOGS_DIR/e2e_tests.log"
     # I don't want to have to check out the Quartus license for each and every
     # commit, so just skip the vsim-related tests here
-    ./src/e2e/python/run.py --skip-vsim || {
+    ./src/e2e/python/run.py --skip-vsim >"$logs" 2>&1 || {
         echo "End-to-end tests failed."
+        echo "See $logs for details."
         exit 1
     }
     echo ""
 fi
 
-if [ -z "${SKIP_SRC_TEST_PYTHON:-}" ]; then
+##### Python-related tests #####################################################
+
+if [ -n "${SKIP_PYTHON:-}" ]; then
+    SKIP_PYTHON_SRC_TEST='1'
+    SKIP_PYTHON_SRC_E2E='1'
+    SKIP_PYTHON_DOCS='1'
+fi
+
+if [ -z "${SKIP_PYTHON_SRC_TEST:-}" ]; then
     # It seems we need to be in the right directory for pyright to accept the relative imports
     cd ./src/test/python
-    echo "Checking Python code in $(pwd) (skip by defining SKIP_SRC_TEST_PYTHON)..."
-    pyright . --project .pyrightconfig.json
-    pylint  . --rcfile  ../../../.pylintrc
-    cd - >/dev/null
-    echo ""
-fi
-
-if [ -z "${SKIP_SRC_E2E_PYTHON:-}" ]; then
-    # It seems we need to be in the right directory for pyright to accept the relative imports
-    cd ./src/e2e/python
-    echo "Checking Python code in $(pwd) (skip by defining SKIP_SRC_E2E_PYTHON)..."
-    pyright . --project .pyrightconfig.json
-    pylint  . --rcfile  ../../../.pylintrc
-    cd - >/dev/null
-    echo ""
-fi
-
-if [ -z "${SKIP_DOCS_PYTHON:-}" ]; then
-    # It seems we need to be in the right directory for pyright to accept the relative imports
-    cd ./docs/source
-    echo "Checking Python code in $(pwd) (skip by defining SKIP_DOCS_PYTHON)..."
-    pyright . --project .pyrightconfig.json
-    pylint  . --rcfile  ../../.pylintrc
-    cd - >/dev/null
-    echo ""
-fi
-
-if [ -z "${SKIP_DOCS:-}" ]; then
-    echo "Testing documentation website..."
-    cd docs
-    make html >/dev/null || {
-        echo "Command 'make html' failed"
+    echo "Checking Python code in $(pwd) (skip by defining SKIP_PYTHON or SKIP_PYTHON_SRC_TEST)..."
+    logs="$LOGS_DIR/python_src_test.log"
+    pyright . --project .pyrightconfig.json >"$logs" 2>&1 || {
+        echo "pyright checks failed."
+        echo "See $logs for details."
         exit 1
     }
-    make linkcheck || {
+    pylint . --rcfile ../../../.pylintrc >>"$logs" 2>&1 || {
+        echo "pylint checks failed."
+        echo "See $logs for details."
+        exit 1
+    }
+    cd - >/dev/null
+    echo ""
+fi
+
+if [ -z "${SKIP_PYTHON_SRC_E2E:-}" ]; then
+    # It seems we need to be in the right directory for pyright to accept the relative imports
+    cd ./src/e2e/python
+    echo "Checking Python code in $(pwd) (skip by defining SKIP_PYTHON or SKIP_PYTHON_SRC_E2E)..."
+    logs="$LOGS_DIR/python_src_e2e.log"
+    pyright . --project .pyrightconfig.json >"$logs" 2>&1 || {
+        echo "pyright checks failed."
+        echo "See $logs for details."
+        exit 1
+    }
+    pylint . --rcfile ../../../.pylintrc >>"$logs" 2>&1 || {
+        echo "pylint checks failed."
+        echo "See $logs for details"
+        exit 1
+    }
+    cd - >/dev/null
+    echo ""
+fi
+
+if [ -z "${SKIP_PYTHON_DOCS:-}" ]; then
+    # It seems we need to be in the right directory for pyright to accept the relative imports
+    cd ./docs/source
+    echo "Checking Python code in $(pwd) (skip by defining SKIP_PYTHON or SKIP_PYTHON_DOCS)..."
+    logs="$LOGS_DIR/python_docs.log"
+    pyright . --project .pyrightconfig.json >"$logs" 2>&1 || {
+        echo "pyright checks failed."
+        echo "See $logs for details."
+        exit 1
+    }
+    pylint . --rcfile ../../.pylintrc >>"$logs" 2>&1 || {
+        echo "pylint checks failed."
+        echo "See $logs for details."
+        exit 1
+    }
+    cd - >/dev/null
+    echo ""
+fi
+
+##### Documentation website checks #############################################
+
+if [ -z "${SKIP_DOCS:-}" ]; then
+    echo "Testing documentation website (skip by defining SKIP_DOCS)..."
+    logs="$LOGS_DIR/docs.log"
+    cd docs
+    make html >"$logs" 2>&1 || {
+        echo "Command 'make html' failed"
+        echo "See $logs for details."
+        exit 1
+    }
+    make linkcheck >>"$logs" 2>&1 || {
         echo "Command 'make linkcheck' failed"
+        echo "See $logs for details."
         exit 1
     }
     cd - > /dev/null
+    echo ""
 fi
 
 # If there are whitespace errors, print the offending file names and fail.
